import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <header>
              <h1>UAEU News</h1>
                  <nav>
                      <div>
                          Updates
                      </div>
                      <div>
                          Events
                      </div>
                      <div>
                          Opinions
                      </div>
                  </nav>
          </header>
      </main>
    </>
  )
}
